### ISSUE TITLE
Unfriendly error message when file does not have 'read' permissions

### ISSUE THREAD

**Issue by JerryHue** [DukeManh/OSD_SSG#5]
I created a file (`hello.txt`) and removed the read permissions through `chmod`, `ls` gives me the following output:

```--w--w---- 1 gerardo gerardo 45 Sep 16 13:07 hello.txt```

Running the command `ts-node src/index.ts -i hello.txt` gives me the following error message:

```
Error: EACCES: permission denied, open 'hello.txt'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at processFile (/home/gerardo/workspace/osd-ssg/src/index.ts:93:19)
    at Object.<anonymous> (/home/gerardo/workspace/osd-ssg/src/index.ts:196:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/gerardo/.local/lib/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gerardo/.local/lib/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'hello.txt'
}
```

**Comment by JerryHue** [comment]
I suggest that, for this error, the most recommended would be to let the user know that the program cannot access the file due to them not having read permissions. Something along the lines of `The file 'hello.txt' cannot be read due to having insufficient permissions` would be fine.

**Comment by DukeManh** [comment]
I'm closing this as I think users would know what the error is, and it's not important for now.
